In [1]:
import numpy as np

In [2]:
a = np.arange(12)
print(type(a))
a

<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
print(a.shape)
a.shape = 3, 4
a

(12,)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print(a[2])
print(a[2, 1])
print(a[:, 1])

[ 8  9 10 11]
9
[1 5 9]


In [5]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
from random import random
from time import perf_counter as pc

In [12]:
t0 = pc()
with open('10M-floats.txt', 'a') as fd:
    for i in range(10000000):
        fd.write(str(random()) + '\n')
print(pc() - t0)

9.546551270999771


In [13]:
t0 = pc()
floats = np.loadtxt('10M-floats.txt')
print(pc() - t0)
print(floats[0], floats[-1])

25.144014012999833
0.08253667024358646 0.6135606607944284


In [14]:
t0 = pc()
np.save('10M-floats', floats)
print(pc() - t0)

0.058867495999948005


In [16]:
t0 = pc()
floats2 = np.load('10M-floats.npy', 'r+')
print(pc() - t0)
print(floats2[0], floats2[-1])

0.003254917999583995
0.08253667024358646 0.6135606607944284
